onEvent('recipes', event => {

    event.replaceInput({id:'thermal:saw_blade'}, 'minecraft:copper_ingot', 'thermal:steel_block')
	event.replaceInput({id:'create:crafting/kinetics/mechanical_saw'}, 'minecraft:iron_ingot', 'thermal:saw_blade')
	//event.replaceInput({}, 'industrialforegoing:plastic', 'pneumaticcraft:plastic')
	event.replaceInput({id:'refinedstorage:raw_basic_processor'}, 'minecraft:iron_ingot', 'thermal:steel_nugget')
	event.replaceInput({id:'refinedstorage:raw_improved_processor'}, 'minecraft:gold_ingot', 'thermal:electrum_nugget')
	event.replaceInput({id:'refinedstorage:raw_advanced_processor'}, 'minecraft:diamond', 'kubejs:enriched_diamond_nugget')
	event.replaceInput({id:'extendedcrafting:advanced_table'}, 'extendedcrafting:basic_table', 'minecraft:crafting_table')
    event.replaceInput({id:'sophisticatedbackpacks:upgrade_base'}, 'minecraft:string', 'immersiveengineering:hemp_fabric')
    event.replaceInput({id:'sophisticatedbackpacks:upgrade_base'}, 'minecraft:iron_ingot', 'thermal:steel_ingot')
	event.replaceInput({id:'rftoolsbase:machine_base'}, 'minecraft:gold_nugget', 'thermal:electrum_nugget')
	event.replaceInput({id:'ironjetpacks:iron_jetpack'}, 'ironjetpacks:wood', '')
	event.replaceInput({id:'thermal:augments/item_filter_augment'}, 'thermal:signalum_ingot', 'thermal:invar_ingot')
	event.replaceInput({id:'thermal:augments/fluid_filter_augment'}, 'thermal:signalum_ingot', 'thermal:invar_ingot')
	event.replaceInput({id:'thermal:augments/machine_speed_augment'}, 'thermal:rf_coil', 'kubejs:augment_base')
	event.replaceInput({id:'thermal:augments/machine_efficiency_augment'}, 'thermal:rf_coil', 'kubejs:augment_base')
	event.replaceInput({id:'thermal:augments/machine_efficiency_augment'}, 'thermal:lumium_plate', 'thermal:constantan_plate')
	event.replaceInput({id:'thermal:augments/dynamo_fuel_augment'}, '#thermal:glass_hardened', 'kubejs:augment_base')
	event.replaceInput({input:'mekanism:dust_quartz'}, 'mekanism:dust_quartz', 'thermal:quartz_dust')
	event.replaceOutput({output:'mekanism:dust_quartz'}, 'mekanism:dust_quartz', 'thermal:quartz_dust')
	event.replaceInput({input:'thermal:slag'}, 'thermal:slag', 'immersiveengineering:slag')
	event.replaceOutput({output:'thermal:slag'}, 'thermal:slag', 'immersiveengineering:slag')
	event.replaceInput({id:'pneumaticcraft:flux_compressor'}, 'minecraft:blast_furnace', 'thermal:dynamo_compression')
	event.replaceInput({id:'thermal:machine_crystallizer'}, 'thermal:invar_plate', 'thermal:signalum_plate')

})	