onEvent('recipes', (event) => {
    event.stonecutting("thermal:machine_furnace", 'kubejs:basic_versatile_frame')
    event.stonecutting("thermal:machine_pulverizer", 'kubejs:basic_versatile_frame')
    event.stonecutting("thermal:machine_smelter", 'kubejs:basic_versatile_frame')
    event.stonecutting("thermal:machine_centrifuge", 'kubejs:basic_versatile_frame')
    event.stonecutting("thermal:machine_press", 'kubejs:basic_versatile_frame')
    event.stonecutting("thermal:machine_crucible", 'kubejs:basic_versatile_frame')
    event.stonecutting("thermal:machine_chiller", 'kubejs:basic_versatile_frame')
    event.stonecutting("thermal:machine_refinery", 'kubejs:basic_versatile_frame')
    event.stonecutting("thermal:machine_bottler", 'kubejs:basic_versatile_frame')
    event.stonecutting("thermal:machine_crystallizer", 'kubejs:basic_versatile_frame')
    event.stonecutting("mekanism:crusher", 'kubejs:basic_versatile_frame')
    event.stonecutting("mekanism:energized_smelter", 'kubejs:basic_versatile_frame')
    event.stonecutting("mekanism:metallurgic_infuser", 'kubejs:basic_versatile_frame')
    event.stonecutting("mekanism:enrichment_chamber", 'kubejs:basic_versatile_frame')
    event.stonecutting("pneumaticcraft:thermopneumatic_processing_plant", 'kubejs:basic_versatile_frame')


    event.stonecutting("mekanism:purification_chamber", 'kubejs:advanced_versatile_frame')
    event.stonecutting("mekanism:electrolytic_separator", 'kubejs:advanced_versatile_frame')
    event.stonecutting("mekanism:pressurized_reaction_chamber", 'kubejs:advanced_versatile_frame')
    event.stonecutting("mekanism:rotary_condensentrator", 'kubejs:advanced_versatile_frame')
    event.stonecutting("mekanism:chemical_oxidizer", 'kubejs:advanced_versatile_frame')
    event.stonecutting("industrialforegoing:dissolution_chamber", 'kubejs:advanced_versatile_frame')
})